---
#- name: Socks tunnel setup
#  hosts: all
#  gather_facts: false
#  roles:
#  - role: ansible-role-event-socks-tunnel
#    run_once: true
#    delegate_to: localhost
#    vars:
#      acc_id: "{{ account_triname }}"
#      transaction_id: "{{ tower_job_id }}"

- name: Ansible PlayBook - Instalacion Qualys Linux
  hosts: all
  gather_facts: false
  
- set_fact:
    run_role: |
      {% if role == 'Contro_M_Tasks' %}
      ['prueba_uno/agregar_lineas']
      {% elif role == 'Contro_M_Fetchs' %}
      ['prueba_dos/llamar_api']
      {% else %}
      ['No_selecciono_ninguna_tarea']
      {% endif %}

- name: Resultado de la seleccion del role
  assert:
    that:
      - "'No_selecciono_ninguna_role' not in run_playbook"
    fail_msg: "run_role"
    success_msg: "Ha seleccionado: {{ run_playbook | replace('\n', '') }}"
  run_once: true
  delegate_to: localhost

- name: Inicia tareas {{ run_playbook }}
  include_tasks: "{{ roles }}"
  loop: "{{ run_role }}"
  loop_control:
    loop_var: roles